# Assignment 5

## 1. Choose a REGRESSION dataset (reusing bikeshare is allowed), perform a test/train split, and build a regression model (just like in assignment 3), and calculate the 
    + Training Error (MSE, MAE)
    + Testing Error (MSE, MAE)
## 2. Choose a CLASSIFICATION dataset (not the adult.data set, The UCI repository has many datasets as well as Kaggle), perform test/train split and create a classification model (your choice but DecisionTree is fine). Calculate 
    + Accuracy
    + Confusion Matrix
    + Classifcation Report
    
## 3. (Bonus) See if you can improve the classification model's performance with any tricks you can think of (modify features, remove features, polynomial features)

# 1. Choose a REGRESSION dataset (reusing bikeshare is allowed), perform a test/train split, and build a regression model (just like in assignment 3), and calculate the
+ Training Error (MSE, MAE)
+ Testing Error (MSE, MAE)

In [1]:
# linear regression using bikeshare

import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = 20, 10
import pandas as pd
import numpy as np
from sklearn import linear_model

day_hour_count = pd.read_csv("C:/Users/erinp/Desktop/mlnn/data/bikeshare_hour_count.csv")
day_hour_count

hour  monday  tuesday  wednesday  thursday  friday  saturday  sunday
0     0.0    21.0     34.0       43.0      47.0    51.0      89.0   106.0
1     0.1    39.0     22.0       27.0      37.0    56.0      87.0   100.0
2     0.2    31.0     24.0       26.0      42.0    50.0      98.0    77.0
3     0.3    26.0     27.0       25.0      29.0    52.0      99.0    87.0
4     0.4    19.0     24.0       29.0      29.0    50.0      98.0    69.0
..    ...     ...      ...        ...       ...     ...       ...     ...
235  23.5    36.0     65.0       60.0      94.0    80.0      93.0    28.0
236  23.6    37.0     61.0       66.0     100.0    81.0      95.0    28.0
237  23.7    30.0     42.0       49.0      80.0   101.0     105.0    27.0
238  23.8    33.0     52.0       47.0      79.0    91.0      93.0    24.0
239  23.9    34.0     33.0       48.0      65.0   105.0     111.0    23.0

[240 rows x 8 columns]

In [3]:
from sklearn.model_selection import train_test_split

In [7]:
# using saturday since no null values
saturday = day_hour_count[["hour", "saturday"]].copy()

In [16]:
x_train, x_test, y_train, y_test = train_test_split(saturday["hour"].values.reshape(-1,1),saturday["saturday"], test_size=.20)

In [17]:
x_train

array([[21.4],
       [ 7. ],
       [ 6.6],
       [ 1.7],
       [14.1],
       [12. ],
       [ 1.1],
       [17.2],
       [ 5.4],
       [15.8],
       [21.2],
       [ 7.8],
       [14.5],
       [ 4. ],
       [12.5],
       [15.4],
       [22.3],
       [20.7],
       [16.8],
       [ 0. ],
       [15.2],
       [20.9],
       [11.7],
       [22.8],
       [21.5],
       [ 8.3],
       [11.2],
       [13. ],
       [ 7.1],
       [17.1],
       [10. ],
       [ 3.2],
       [ 1.4],
       [ 8. ],
       [10.9],
       [13.5],
       [ 8.2],
       [12.6],
       [ 6.8],
       [19.7],
       [19.3],
       [23.7],
       [ 4.6],
       [ 6.5],
       [ 5.5],
       [15.3],
       [11.6],
       [ 5.6],
       [21.9],
       [23.4],
       [ 5.8],
       [ 9.2],
       [11. ],
       [ 0.8],
       [ 4.2],
       [15.6],
       [18. ],
       [ 4.9],
       [ 0.5],
       [21.7],
       [10.2],
       [16.3],
       [10.4],
       [14.4],
       [21.3],
       [12.1],
       [ 3

In [22]:
from sklearn.linear_model import LinearRegression
model = linear_model.LinearRegression()

In [23]:
model.fit(x_train, y_train)

LinearRegression()

In [24]:
model.predict(x_test)

array([160.22728544, 278.39500116,  87.90049392, 178.56365512,
       188.75052716, 258.02125707, 180.60102953, 115.40504844,
       317.10511493, 154.11516221, 166.33940866, 190.78790157,
       146.98435178, 173.4702191 , 329.32936138, 206.06820964,
       277.37631395, 305.89955568, 216.25508168, 192.82527598,
       281.45106277, 181.61971673, 122.53585887, 316.08642772,
       215.23639448, 295.71268363, 245.79701061, 270.24550352,
        98.08736596, 185.69446555, 247.83438502,  99.10605317,
       177.54496791, 194.86265039, 248.85307223, 234.59145136,
       113.36767403, 129.6666693 ,  92.99392994, 279.41368836,
       237.64751298, 291.63793482, 105.2181764 , 184.67577835,
       236.62882577, 186.71315275, 101.14342758, 110.31161242])

In [33]:
# train MSE
from sklearn import metrics

metrics.mean_squared_error(y_train, model.predict(x_train))

21379.189386024012

In [34]:
# train MAE
metrics.mean_absolute_error(y_train, model.predict(x_train))

130.64027011222015

In [32]:
# test MSE
metrics.mean_squared_error(y_test, model.predict(x_test))

19379.106567754006

In [35]:
# test MAE
metrics.mean_absolute_error(y_test, model.predict(x_test))

118.0618333805761

## 2. Choose a CLASSIFICATION dataset (not the adult.data set, The UCI repository has many datasets as well as Kaggle), perform test/train split and create a classification model (your choice but DecisionTree is fine). Calculate 
    + Accuracy
    + Confusion Matrix
    + Classifcation Report

In [67]:
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
plt.rcParams['figure.figsize'] = (20, 6)
plt.rcParams['font.size'] = 14
import pandas as pd

In [150]:
heart = pd.read_csv("C:/Users/erinp/Desktop/mlnn/data/Heart.csv")
heart

Unnamed: 0  Age  Sex     ChestPain  RestBP  Chol  Fbs  RestECG  MaxHR  \
0             1   63    1       typical     145   233    1        2    150   
1             2   67    1  asymptomatic     160   286    0        2    108   
2             3   67    1  asymptomatic     120   229    0        2    129   
3             4   37    1    nonanginal     130   250    0        0    187   
4             5   41    0    nontypical     130   204    0        2    172   
..          ...  ...  ...           ...     ...   ...  ...      ...    ...   
298         299   45    1       typical     110   264    0        0    132   
299         300   68    1  asymptomatic     144   193    1        0    141   
300         301   57    1  asymptomatic     130   131    0        0    115   
301         302   57    0    nontypical     130   236    0        2    174   
302         303   38    1    nonanginal     138   175    0        0    173   

     ExAng  Oldpeak  Slope   Ca        Thal  AHD  
0        0      2.3      3  0.0       fixed   No  
1        1      1.5      2  3.0      normal  Yes  
2        1      2.6      2  2.0  reversable  Yes  
3        0      3.5      3  0.0      normal   No  
4        0      1.4      1  0.0      normal   No  
..     ...      ...    ...  ...         ...  ...  
298      0      1.2      2  0.0  reversable  Yes  
299      0      3.4      2  2.0  reversable  Yes  
300      1      1.2      2  1.0  reversable  Yes  
301      0      0.0      2  1.0      normal  Yes  
302      0      0.0      1  NaN      normal   No  

[303 rows x 15 columns]

In [151]:
heart.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [152]:
non_numeric_columns = ['Unnamed: 0', 'ChestPain','Thal']

In [153]:
from sklearn.tree import DecisionTreeClassifier

In [154]:
model = DecisionTreeClassifier(criterion='entropy')

In [155]:
x = heart.copy().drop(non_numeric_columns, axis=1)
x

Age  Sex  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  Slope   Ca  \
0     63    1     145   233    1        2    150      0      2.3      3  0.0   
1     67    1     160   286    0        2    108      1      1.5      2  3.0   
2     67    1     120   229    0        2    129      1      2.6      2  2.0   
3     37    1     130   250    0        0    187      0      3.5      3  0.0   
4     41    0     130   204    0        2    172      0      1.4      1  0.0   
..   ...  ...     ...   ...  ...      ...    ...    ...      ...    ...  ...   
298   45    1     110   264    0        0    132      0      1.2      2  0.0   
299   68    1     144   193    1        0    141      0      3.4      2  2.0   
300   57    1     130   131    0        0    115      1      1.2      2  1.0   
301   57    0     130   236    0        2    174      0      0.0      2  1.0   
302   38    1     138   175    0        0    173      0      0.0      1  NaN   

     AHD  
0     No  
1    Yes  
2    Yes  
3     No  
4     No  
..   ...  
298  Yes  
299  Yes  
300  Yes  
301  Yes  
302   No  

[303 rows x 12 columns]

In [159]:
# drop NaN values in Ca
x = x.dropna()
x


Age  Sex  RestBP  Chol  Fbs  RestECG  MaxHR  ExAng  Oldpeak  Slope   Ca  \
0     63    1     145   233    1        2    150      0      2.3      3  0.0   
1     67    1     160   286    0        2    108      1      1.5      2  3.0   
2     67    1     120   229    0        2    129      1      2.6      2  2.0   
3     37    1     130   250    0        0    187      0      3.5      3  0.0   
4     41    0     130   204    0        2    172      0      1.4      1  0.0   
..   ...  ...     ...   ...  ...      ...    ...    ...      ...    ...  ...   
297   57    0     140   241    0        0    123      1      0.2      2  0.0   
298   45    1     110   264    0        0    132      0      1.2      2  0.0   
299   68    1     144   193    1        0    141      0      3.4      2  2.0   
300   57    1     130   131    0        0    115      1      1.2      2  1.0   
301   57    0     130   236    0        2    174      0      0.0      2  1.0   

     AHD  
0     No  
1    Yes  
2    Yes  
3     No  
4     No  
..   ...  
297  Yes  
298  Yes  
299  Yes  
300  Yes  
301  Yes  

[299 rows x 12 columns]

In [160]:
model.fit(x.drop(['AHD'], axis=1), x.AHD)

DecisionTreeClassifier(criterion='entropy')

In [161]:
list(zip(x.drop(['AHD'], axis=1).columns, model.feature_importances_))

[('Age', 0.06056647000188924),
 ('Sex', 0.08126731378027524),
 ('RestBP', 0.12407349834321237),
 ('Chol', 0.10582430680990226),
 ('Fbs', 0.0346297082129495),
 ('RestECG', 0.028687627488659176),
 ('MaxHR', 0.06766038904194911),
 ('ExAng', 0.08036234897087592),
 ('Oldpeak', 0.11923805801640353),
 ('Slope', 0.09029789894339078),
 ('Ca', 0.20739238039049282)]

In [163]:
x_train, x_test, y_train, y_test = train_test_split(x.drop(['AHD'], axis=1),x.AHD, test_size=.20)

In [164]:
x.shape, x_train.shape, x_test.shape

((299, 12), (239, 11), (60, 11))

In [165]:
model.fit(x_train, y_train)

DecisionTreeClassifier(criterion='entropy')

In [166]:
test_predictions = model.predict(x_test)

In [167]:
test_predictions

array(['No', 'Yes', 'No', 'Yes', 'No', 'Yes', 'No', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes',
       'Yes', 'No', 'No', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'Yes',
       'No', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No', 'Yes', 'No',
       'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'Yes', 'No', 'No', 'Yes', 'No',
       'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes', 'Yes', 'No'],
      dtype=object)

In [168]:
y_test

46      No
208     No
94      No
121    Yes
5       No
241     No
290    Yes
67      No
201     No
299    Yes
253     No
55     Yes
225     No
242     No
274    Yes
203     No
130     No
45     Yes
112     No
131     No
106    Yes
70      No
276     No
58      No
108    Yes
86      No
251    Yes
212     No
64     Yes
157    Yes
3       No
36     Yes
264    Yes
248    Yes
194     No
200     No
223    Yes
4       No
72     Yes
19      No
260     No
73     Yes
59      No
80      No
228    Yes
56     Yes
26      No
93      No
76     Yes
87      No
261    Yes
105     No
126    Yes
129     No
65     Yes
219     No
136    Yes
155    Yes
243    Yes
78      No
Name: AHD, dtype: object

In [169]:
from sklearn.metrics import (accuracy_score, 
                             classification_report, 
                             confusion_matrix
                            )

In [170]:
accuracy_score(y_test, test_predictions)

0.7666666666666667

In [171]:
confusion_matrix(y_test, test_predictions)

array([[22, 12],
       [ 2, 24]], dtype=int64)

In [173]:
print(classification_report(y_test, test_predictions))

              precision    recall  f1-score   support

          No       0.92      0.65      0.76        34
         Yes       0.67      0.92      0.77        26

    accuracy                           0.77        60
   macro avg       0.79      0.79      0.77        60
weighted avg       0.81      0.77      0.77        60

